package templates

import "jordanella.com/pocket-tcg-go/internal/cv"

// Template constant definitions (exported for use across packages)
var (
	//1Star1 = cv.Template{Name: "1star1"}
	//1star2 = cv.Template{Name: "1star2"}
	//1Star3 = cv.Template{Name: "1star3"}
	//1Star4 = cv.Template{Name: "1star4"}
	//1Star5 = cv.Template{Name: "1star5"}
	//1Star6card4 = cv.Template{Name: "1star6card4"}
	//1Star6card6 = cv.Template{Name: "1star6card6"}
	//3Diamond1 = cv.Template{Name: "3diamond1"}
	//3Diamond2 = cv.Template{Name: "3diamond2"}
	//3Diamond3 = cv.Template{Name: "3diamond3"}
	//3Diamond4 = cv.Template{Name: "3diamond4"}
	//3Diamond5 = cv.Template{Name: "3diamond5"}
	//6CardPackIndicator = cv.Template{Name: "6cardpackindicator"}
	//99cn = cv.Template{Name: "99cn"}
	//99de = cv.Template{Name: "99de"}
	//99en = cv.Template{Name: "99en"}
	//99es = cv.Template{Name: "99es"}
	//99fr = cv.Template{Name: "99fr"}
	//99it = cv.Template{Name: "99it"}
	//99jp = cv.Template{Name: "99jp"}
	//99ko = cv.Template{Name: "99ko"}
	//99pt = cv.Template{Name: "99pt"}
	Accept                      = cv.Template{Name: "Accept"}
	Accepted                    = cv.Template{Name: "Accepted", Region: &cv.Region{X1: 165, Y1: 250, X2: 190, Y2: 275}}
	Accepted2                   = cv.Template{Name: "Accepted2", Region: &cv.Region{X1: 87, Y1: 401, X2: 99, Y2: 412}}
	Account                     = cv.Template{Name: "Account", Region: &cv.Region{X1: 24, Y1: 158, X2: 57, Y2: 189}}
	Account2                    = cv.Template{Name: "Account2", Region: &cv.Region{X1: 56, Y1: 435, X2: 108, Y2: 460}}
	Add                         = cv.Template{Name: "Add", Region: &cv.Region{X1: 226, Y1: 100, X2: 270, Y2: 135}}
	Add2                        = cv.Template{Name: "Add2", Region: &cv.Region{X1: 120, Y1: 188, X2: 140, Y2: 208}}
	Album                       = cv.Template{Name: "Album", Region: &cv.Region{X1: 15, Y1: 455, X2: 40, Y2: 475}}
	App                         = cv.Template{Name: "App"}
	Approve                     = cv.Template{Name: "Approve"}
	Badge                       = cv.Template{Name: "Badge"}
	Birth                       = cv.Template{Name: "Birth", Region: &cv.Region{X1: 116, Y1: 352, X2: 138, Y2: 389}}
	Booster                     = cv.Template{Name: "Booster"}
	Border                      = cv.Template{Name: "Border"}
	Bulba                       = cv.Template{Name: "Bulba"}
	Button                      = cv.Template{Name: "Button"}
	Button2                     = cv.Template{Name: "Button2", Region: &cv.Region{X1: 75, Y1: 340, X2: 195, Y2: 530}}
	Card                        = cv.Template{Name: "Card", Region: &cv.Region{X1: 160, Y1: 330, X2: 200, Y2: 370}}
	ChooseEevee                 = cv.Template{Name: "ChooseEevee"}
	ChooseErika                 = cv.Template{Name: "ChooseErika"}
	ChosenTag                   = cv.Template{Name: "ChosenTag"}
	Cinematic                   = cv.Template{Name: "Cinematic", Region: &cv.Region{X1: 0, Y1: 46, X2: 20, Y2: 70}}
	Claim                       = cv.Template{Name: "Claim"}
	ClaimAll                    = cv.Template{Name: "ClaimAll"}
	ClaimAllDisabled            = cv.Template{Name: "ClaimAllDisabled"}
	ClearAll                    = cv.Template{Name: "clearAll", Region: &cv.Region{X1: 191, Y1: 498, X2: 207, Y2: 514}}
	CloseDuringPack             = cv.Template{Name: "closeduringpack", Region: &cv.Region{X1: 241, Y1: 377, X2: 269, Y2: 407}}
	CollectDailies              = cv.Template{Name: "CollectDailies"}
	CommunityShowcase           = cv.Template{Name: "CommunityShowcase", Region: &cv.Region{X1: 174, Y1: 464, X2: 189, Y2: 479}}
	Complete                    = cv.Template{Name: "Complete", Region: &cv.Region{X1: 215, Y1: 371, X2: 264, Y2: 418}}
	Confirm                     = cv.Template{Name: "Confirm", Region: &cv.Region{X1: 110, Y1: 350, X2: 150, Y2: 404}}
	ConfirmPack                 = cv.Template{Name: "ConfirmPack", Region: &cv.Region{X1: 121, Y1: 465, X2: 140, Y2: 485}}
	Country                     = cv.Template{Name: "Country", Region: &cv.Region{X1: 105, Y1: 396, X2: 121, Y2: 406}}
	CountrySelect               = cv.Template{Name: "CountrySelect", Region: &cv.Region{X1: 93, Y1: 471, X2: 122, Y2: 485}}
	CountrySelect2              = cv.Template{Name: "CountrySelect2", Region: &cv.Region{X1: 110, Y1: 134, X2: 164, Y2: 160}}
	Crown1                      = cv.Template{Name: "crown1"}
	Crown2                      = cv.Template{Name: "crown2"}
	Crown3                      = cv.Template{Name: "crown3"}
	Crown4                      = cv.Template{Name: "crown4"}
	Crown5                      = cv.Template{Name: "crown5"}
	DailyMissions               = cv.Template{Name: "DailyMissions", Region: &cv.Region{X1: 37, Y1: 130, X2: 64, Y2: 156}}
	Delete                      = cv.Template{Name: "Delete"}
	Delete2                     = cv.Template{Name: "Delete2"}
	Delete3                     = cv.Template{Name: "Delete3"}
	DeleteAll                   = cv.Template{Name: "DeleteAll", Region: &cv.Region{X1: 200, Y1: 340, X2: 250, Y2: 530}}
	DeleteFriend                = cv.Template{Name: "DeleteFriend"}
	Deluxe1Star1                = cv.Template{Name: "deluxe1star1"}
	Deluxe1Star2                = cv.Template{Name: "deluxe1star2"}
	Deluxe3Diamond1             = cv.Template{Name: "deluxe3diamond1"}
	Deluxe3Diamond2             = cv.Template{Name: "deluxe3diamond2"}
	DeluxeFullArt1              = cv.Template{Name: "deluxefullart1"}
	DeluxeFullArt2              = cv.Template{Name: "deluxefullart2"}
	DeluxeImmersive1            = cv.Template{Name: "deluxeimmersive1"}
	DeluxeImmersive2            = cv.Template{Name: "deluxeimmersive2"}
	DeluxeShiny2star2           = cv.Template{Name: "deluxeshiny2star2"}
	DeluxeTrainer1              = cv.Template{Name: "deluxetrainer1"}
	DeluxeTrainer2              = cv.Template{Name: "deluxetrainer2"}
	DexMissions                 = cv.Template{Name: "DexMissions", Region: &cv.Region{X1: 18, Y1: 215, X2: 30, Y2: 227}}
	Eevee                       = cv.Template{Name: "Eevee"}
	Empty                       = cv.Template{Name: "empty", Region: &cv.Region{X1: 42, Y1: 163, X2: 66, Y2: 185}}
	Erase                       = cv.Template{Name: "Erase", Region: &cv.Region{X1: 15, Y1: 500, X2: 68, Y2: 520}}
	Erika                       = cv.Template{Name: "Erika"}
	Error                       = cv.Template{Name: "Error"}
	FeatureUnlocked1            = cv.Template{Name: "FeatureUnlocked1"}
	FirstAnniversaryCelebration = cv.Template{Name: "FirstAnniversaryCelebration", Region: &cv.Region{X1: 223, Y1: 179, X2: 231, Y2: 187}}
	FirstMission                = cv.Template{Name: "FirstMission", Region: &cv.Region{X1: 120, Y1: 185, X2: 150, Y2: 215}}
	Friend                      = cv.Template{Name: "Friend"}
	Friend2                     = cv.Template{Name: "Friend2"}
	FriendIDSearch              = cv.Template{Name: "FriendIDSearch", Region: &cv.Region{X1: 215, Y1: 252, X2: 240, Y2: 277}}
	Friends                     = cv.Template{Name: "Friends", Region: &cv.Region{X1: 84, Y1: 463, X2: 100, Y2: 475}}
	FullArt1                    = cv.Template{Name: "fullart1"}
	FullArt2                    = cv.Template{Name: "fullart2"}
	FullArt3                    = cv.Template{Name: "fullart3"}
	FullArt4                    = cv.Template{Name: "fullart4"}
	FullArt5                    = cv.Template{Name: "fullart5"}
	GholdengoEmblem             = cv.Template{Name: "GholdengoEmblem"}
	Gimmighoul1                 = cv.Template{Name: "gimmighoul1"}
	Gimmighoul2                 = cv.Template{Name: "gimmighoul2"}
	Gimmighoul3                 = cv.Template{Name: "gimmighoul3"}
	Gimmighoul4                 = cv.Template{Name: "gimmighoul4"}
	GotAllMissions              = cv.Template{Name: "GotAllMissions", Region: &cv.Region{X1: 244, Y1: 406, X2: 273, Y2: 449}}
	Gray                        = cv.Template{Name: "Gray", Region: &cv.Region{X1: 46, Y1: 368, X2: 103, Y2: 411}}
	Home                        = cv.Template{Name: "Home", Region: &cv.Region{X1: 20, Y1: 500, X2: 55, Y2: 530}}
	Hourglass                   = cv.Template{Name: "Hourglass", Region: &cv.Region{X1: 178, Y1: 193, X2: 251, Y2: 282}}
	Hourglass1                  = cv.Template{Name: "Hourglass1", Region: &cv.Region{X1: 98, Y1: 184, X2: 151, Y2: 224}}
	Hourglass2                  = cv.Template{Name: "Hourglass2", Region: &cv.Region{X1: 236, Y1: 198, X2: 266, Y2: 226}}
	Hourglass3                  = cv.Template{Name: "Hourglass3", Region: &cv.Region{X1: 175, Y1: 165, X2: 255, Y2: 235}}
	HourGlassAndPokeGoldPack    = cv.Template{Name: "HourGlassAndPokeGoldPack", Region: &cv.Region{X1: 49, Y1: 449, X2: 70, Y2: 474}}
	HourglassPack               = cv.Template{Name: "HourglassPack", Region: &cv.Region{X1: 60, Y1: 440, X2: 90, Y2: 480}}
	Immersive1                  = cv.Template{Name: "immersive1"}
	Immersive2                  = cv.Template{Name: "immersive2"}
	Immersive3                  = cv.Template{Name: "immersive3"}
	Immersive4                  = cv.Template{Name: "immersive4"}
	Immersive5                  = cv.Template{Name: "immersive5"}
	InHamburgerMenu             = cv.Template{Name: "inHamburgerMenu", Region: &cv.Region{X1: 252, Y1: 78, X2: 263, Y2: 92}}
	InsideTrade                 = cv.Template{Name: "insideTrade"}
	Lag1                        = cv.Template{Name: "lag1"}
	Lag2                        = cv.Template{Name: "lag2"}
	Lag3                        = cv.Template{Name: "lag3"}
	Lag4                        = cv.Template{Name: "lag4"}
	Lag5                        = cv.Template{Name: "lag5"}
	LevelUp                     = cv.Template{Name: "LevelUp", Region: &cv.Region{X1: 100, Y1: 86, X2: 167, Y2: 116}}
	Link                        = cv.Template{Name: "Link", Region: &cv.Region{X1: 51, Y1: 335, X2: 107, Y2: 359}}
	Mail                        = cv.Template{Name: "Mail", Region: &cv.Region{X1: 240, Y1: 70, X2: 270, Y2: 110}}
	Main                        = cv.Template{Name: "Main", Region: &cv.Region{X1: 120, Y1: 316, X2: 143, Y2: 335}}
	Menu                        = cv.Template{Name: "Menu", Region: &cv.Region{X1: 20, Y1: 120, X2: 50, Y2: 150}}
	Mission                     = cv.Template{Name: "Mission", Region: &cv.Region{X1: 115, Y1: 255, X2: 176, Y2: 308}}
	Missions                    = cv.Template{Name: "Missions", Region: &cv.Region{X1: 15, Y1: 456, X2: 18, Y2: 473}}
	MissionWonder               = cv.Template{Name: "missionwonder", Region: &cv.Region{X1: 150, Y1: 159, X2: 176, Y2: 206}}
	MissionDino1                = cv.Template{Name: "Mission_dino1", Region: &cv.Region{X1: 180, Y1: 498, X2: 190, Y2: 508}}
	MissionDino2                = cv.Template{Name: "Mission_dino2", Region: &cv.Region{X1: 136, Y1: 158, X2: 156, Y2: 190}}
	Month                       = cv.Template{Name: "Month", Region: &cv.Region{X1: 100, Y1: 386, X2: 138, Y2: 416}}
	Move                        = cv.Template{Name: "Move", Region: &cv.Region{X1: 136, Y1: 420, X2: 151, Y2: 436}}
	Name                        = cv.Template{Name: "Name", Region: &cv.Region{X1: 190, Y1: 241, X2: 225, Y2: 270}}
	Next                        = cv.Template{Name: "Next", Region: &cv.Region{X1: 120, Y1: 70, X2: 150, Y2: 100}}
	Next2                       = cv.Template{Name: "Next2", Region: &cv.Region{X1: 120, Y1: 70, X2: 150, Y2: 100}}
	NoGifts                     = cv.Template{Name: "NoGifts"}
	NoResponse                  = cv.Template{Name: "NoResponse", Region: &cv.Region{X1: 38, Y1: 281, X2: 57, Y2: 308}}
	NoResponseDark              = cv.Template{Name: "NoResponseDark", Region: &cv.Region{X1: 38, Y1: 281, X2: 57, Y2: 308}}
	Normal1                     = cv.Template{Name: "normal1"}
	Normal2                     = cv.Template{Name: "normal2"}
	Normal3                     = cv.Template{Name: "normal3"}
	Normal4                     = cv.Template{Name: "normal4"}
	Normal5                     = cv.Template{Name: "normal5"}
	NoSave                      = cv.Template{Name: "NoSave"}
	NotEnoughItems              = cv.Template{Name: "notenoughitems", Region: &cv.Region{X1: 92, Y1: 299, X2: 115, Y2: 317}}
	Notifications               = cv.Template{Name: "Notifications", Region: &cv.Region{X1: 170, Y1: 160, X2: 220, Y2: 200}}
	NoWPEnergy                  = cv.Template{Name: "noWPenergy"}
	OK                          = cv.Template{Name: "OK"}
	OK2                         = cv.Template{Name: "OK2", Region: &cv.Region{X1: 0, Y1: 475, X2: 25, Y2: 495}}
	One                         = cv.Template{Name: "One"}
	Opening                     = cv.Template{Name: "Opening", Region: &cv.Region{X1: 170, Y1: 98, X2: 270, Y2: 125}}
	Pack                        = cv.Template{Name: "Pack", Region: &cv.Region{X1: 225, Y1: 273, X2: 235, Y2: 290}}
	Pending                     = cv.Template{Name: "Pending"}
	Pick                        = cv.Template{Name: "Pick", Region: &cv.Region{X1: 60, Y1: 130, X2: 202, Y2: 142}}
	Player                      = cv.Template{Name: "player"}
	Points                      = cv.Template{Name: "Points", Region: &cv.Region{X1: 233, Y1: 400, X2: 264, Y2: 428}}
	Pokeball                    = cv.Template{Name: "Pokeball", Region: &cv.Region{X1: 115, Y1: 97, X2: 174, Y2: 150}}
	PokeGoldPack                = cv.Template{Name: "PokeGoldPack", Region: &cv.Region{X1: 60, Y1: 440, X2: 90, Y2: 480}}
	Premium                     = cv.Template{Name: "Premium", Region: &cv.Region{X1: 225, Y1: 444, X2: 272, Y2: 470}}
	Privacy                     = cv.Template{Name: "Privacy", Region: &cv.Region{X1: 129, Y1: 477, X2: 156, Y2: 494}}
	Proceed                     = cv.Template{Name: "Proceed", Region: &cv.Region{X1: 50, Y1: 394, X2: 86, Y2: 412}}
	Profile                     = cv.Template{Name: "Profile", Region: &cv.Region{X1: 203, Y1: 272, X2: 237, Y2: 300}}
	Rainbow                     = cv.Template{Name: "Rainbow"}
	Rainbow1                    = cv.Template{Name: "rainbow1"}
	Rainbow2                    = cv.Template{Name: "rainbow2"}
	Rainbow3                    = cv.Template{Name: "rainbow3"}
	Rainbow4                    = cv.Template{Name: "rainbow4"}
	Rainbow5                    = cv.Template{Name: "rainbow5"}
	Register                    = cv.Template{Name: "Register", Region: &cv.Region{X1: 124, Y1: 168, X2: 162, Y2: 207}}
	Remove                      = cv.Template{Name: "Remove", Region: &cv.Region{X1: 135, Y1: 355, X2: 160, Y2: 385}}
	Requests                    = cv.Template{Name: "requests", Region: &cv.Region{X1: 97, Y1: 452, X2: 104, Y2: 476}}
	Return                      = cv.Template{Name: "Return", Region: &cv.Region{X1: 121, Y1: 490, X2: 161, Y2: 520}}
	Save                        = cv.Template{Name: "Save", Region: &cv.Region{X1: 30, Y1: 53, X2: 156, Y2: 370}}
	Search                      = cv.Template{Name: "Search", Region: &cv.Region{X1: 205, Y1: 430, X2: 255, Y2: 475}}
	Search2                     = cv.Template{Name: "Search2", Region: &cv.Region{X1: 205, Y1: 430, X2: 255, Y2: 475}}
	SelectExpansion             = cv.Template{Name: "SelectExpansion", Region: &cv.Region{X1: 115, Y1: 140, X2: 160, Y2: 155}}
	Send                        = cv.Template{Name: "Send", Region: &cv.Region{X1: 165, Y1: 250, X2: 190, Y2: 275}}
	Send2                       = cv.Template{Name: "Send2", Region: &cv.Region{X1: 70, Y1: 395, X2: 100, Y2: 420}}
	Settings                    = cv.Template{Name: "Settings", Region: &cv.Region{X1: 90, Y1: 260, X2: 126, Y2: 290}}
	Share                       = cv.Template{Name: "Share"}
	ShinedustItems              = cv.Template{Name: "shinedustItems"}
	Shiny1star1                 = cv.Template{Name: "shiny1star1"}
	Shiny1star2                 = cv.Template{Name: "shiny1star2"}
	Shiny1star3                 = cv.Template{Name: "shiny1star3"}
	Shiny1star4                 = cv.Template{Name: "shiny1star4"}
	Shiny1star5                 = cv.Template{Name: "shiny1star5"}
	Shiny2star1                 = cv.Template{Name: "shiny2star1"}
	Shiny2star2                 = cv.Template{Name: "shiny2star2"}
	Shiny2star3                 = cv.Template{Name: "shiny2star3"}
	Shiny2star4                 = cv.Template{Name: "shiny2star4"}
	Shiny2star5                 = cv.Template{Name: "shiny2star5"}
	Shop                        = cv.Template{Name: "Shop", Region: &cv.Region{X1: 191, Y1: 393, X2: 211, Y2: 411}}
	ShopTicket                  = cv.Template{Name: "ShopTicket", Region: &cv.Region{X1: 25, Y1: 137, X2: 57, Y2: 161}}
	ShopTicketItems             = cv.Template{Name: "shopticketItems"}
	ShowcaseInput               = cv.Template{Name: "ShowcaseInput", Region: &cv.Region{X1: 157, Y1: 498, X2: 225, Y2: 522}}
	ShowcaseLiked               = cv.Template{Name: "ShowcaseLiked", Region: &cv.Region{X1: 98, Y1: 187, X2: 125, Y2: 214}}
	Skip                        = cv.Template{Name: "Skip", Region: &cv.Region{X1: 233, Y1: 486, X2: 272, Y2: 519}}
	Skip2                       = cv.Template{Name: "Skip2", Region: &cv.Region{X1: 233, Y1: 486, X2: 272, Y2: 519}}
	Social                      = cv.Template{Name: "Social", Region: &cv.Region{X1: 120, Y1: 500, X2: 155, Y2: 530}}
	SocialAlert                 = cv.Template{Name: "SocialAlert"}
	SoloBattleMission           = cv.Template{Name: "1solobattlemission", Region: &cv.Region{X1: 108, Y1: 180, X2: 177, Y2: 208}}
	SpeedmodMenu                = cv.Template{Name: "speedmodMenu"}
	StartupErrorX               = cv.Template{Name: "StartupErrorX"}
	Swipe                       = cv.Template{Name: "Swipe", Region: &cv.Region{X1: 34, Y1: 99, X2: 74, Y2: 131}}
	Swipe2                      = cv.Template{Name: "Swipe2"}
	SwipeUp                     = cv.Template{Name: "SwipeUp", Region: &cv.Region{X1: 120, Y1: 70, X2: 150, Y2: 95}}
	Three                       = cv.Template{Name: "Three"}
	Tos                         = cv.Template{Name: "Tos", Region: &cv.Region{X1: 129, Y1: 477, X2: 156, Y2: 494}}
	TosScreen                   = cv.Template{Name: "TosScreen", Region: &cv.Region{X1: 210, Y1: 285, X2: 250, Y2: 315}}
	Trade                       = cv.Template{Name: "Trade", Region: &cv.Region{X1: 100, Y1: 120, X2: 175, Y2: 145}}
	Trainer1                    = cv.Template{Name: "trainer1"}
	Trainer2                    = cv.Template{Name: "trainer2"}
	Trainer3                    = cv.Template{Name: "trainer3"}
	Trainer4                    = cv.Template{Name: "trainer4"}
	Trainer5                    = cv.Template{Name: "trainer5"}
	Trophy                      = cv.Template{Name: "trophy", Region: &cv.Region{X1: 13, Y1: 110, X2: 31, Y2: 129}}
	TrophyPage                  = cv.Template{Name: "trophyPage", Region: &cv.Region{X1: 122, Y1: 375, X2: 161, Y2: 390}}
	Tutorial                    = cv.Template{Name: "Tutorial"}
	Two                         = cv.Template{Name: "Two"}
	Update                      = cv.Template{Name: "Update"}
	UserProfile                 = cv.Template{Name: "UserProfile", Region: &cv.Region{X1: 230, Y1: 120, X2: 260, Y2: 150}}
	Welcome                     = cv.Template{Name: "Welcome", Region: &cv.Region{X1: 110, Y1: 230, X2: 182, Y2: 257}}
	Withdraw                    = cv.Template{Name: "Withdraw", Region: &cv.Region{X1: 165, Y1: 240, X2: 255, Y2: 270}}
	Wonder                      = cv.Template{Name: "Wonder", Region: &cv.Region{X1: 53, Y1: 281, X2: 86, Y2: 310}}
	Wonder2                     = cv.Template{Name: "Wonder2", Region: &cv.Region{X1: 75, Y1: 156, X2: 83, Y2: 167}}
	Wonder3                     = cv.Template{Name: "Wonder3", Region: &cv.Region{X1: 114, Y1: 430, X2: 155, Y2: 441}}
	Wonder4                     = cv.Template{Name: "Wonder4", Region: &cv.Region{X1: 155, Y1: 281, X2: 192, Y2: 315}}
	WonderPick                  = cv.Template{Name: "WonderPick", Region: &cv.Region{X1: 240, Y1: 80, X2: 265, Y2: 100}}
	WPMission                   = cv.Template{Name: "WPMission", Region: &cv.Region{X1: 130, Y1: 170, X2: 170, Y2: 205}}
	WrongItem                   = cv.Template{Name: "wrongItem", Region: &cv.Region{X1: 133, Y1: 369, X2: 148, Y2: 385}}
	Year                        = cv.Template{Name: "Year", Region: &cv.Region{X1: 148, Y1: 348, X2: 256, Y2: 419}}
	//__shiny2star1 = cv.Template{Name: "__shiny2star1"}
)
